version: '3'
services:
  recommendation-service:
    build:
      context: .
      dockerfile: deployment/dev/Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - db-service
    volumes:
      - .:/app
  db-service:
    image: postgres:16.2
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-recommendation
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:  # Define the volume for the database data